### ISSUE TITLE
Zotero 7 compatibility

### ISSUE THREAD

**Issue by pencilheart** [yhmtsai/KeepZotero#3]
Hope to be able to adapt to Zotero 7.

**Comment by temizsu** [comment]
We look forward to the Zotero 7 compatible version.

**Comment by yhmtsai** [comment]
Thanks for bring this up.
Unfortunately, I am busy with other stuff currently.
I may be able to work on this after Novmember.

Update: I have looked into the zotero7 changes. It's more than I thought, so it will need more time

**Comment by yhmtsai** [comment]
Hi @pencilheart and @temizsu . I have updated it to v0.1.0 to support Zotero 7.
Please take a look.
